events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    server {
        listen 443 ssl http2;
        server_name ngulcift.42.fr;

        # Sertifika ve anahtar dosyaları
        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        # SSL/TLS protokol versiyonları (TLSv1.2 ve TLSv1.3)
        ssl_protocols TLSv1.2 TLSv1.3;

        # Web dosyalarının bulunduğu dizin
        root /var/www/html;
        index index.php index.html;

        # Ana dizin istekleri (WordPress için)
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Kurulum ekranını login sayfasına yönlendir
        location = /wp-admin/install.php {
            return 301 /wp-login.php;
        }

        # PHP dosyalarını WordPress (php-fpm)'e yönlendir
        location ~ \.php$ {
            include /etc/nginx/fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # Gizli dosyaları engelle (.htaccess vs)
        location ~ /\.ht {
            deny all;
        }
    }
}
